"""user authentication:

Revision ID: 653167b6738f
Revises: 
Create Date: 2020-10-06 18:25:18.462364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653167b6738f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('billing_adress', sa.String(length=256), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('hash_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_billing_adress'), 'users', ['billing_adress'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_pincode'), 'users', ['pincode'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_pincode'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_billing_adress'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
