"""Added relationship

Revision ID: 894a715ba32f
Revises: 10d57dfabe8a
Create Date: 2020-10-08 13:34:26.957761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894a715ba32f'
down_revision = '10d57dfabe8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutplan', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('workoutplan', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workoutplan', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workoutplan', type_='foreignkey')
    op.drop_column('workoutplan', 'user_id')
    op.drop_column('workoutplan', 'date')
    # ### end Alembic commands ###
